# Generated by Django 3.2.6 on 2021-08-25 20:06

from django.db import migrations, models
import django.db.models.deletion
import home.helper
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('linkedin', 'linkedin'), ('whatsapp', 'whatsapp'), ('github', 'github'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram')], max_length=30, verbose_name='Social Media')),
                ('url', models.URLField(verbose_name='Social Media Link')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Account Image')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
            ],
            options={
                'verbose_name_plural': 'Social Account',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('phone', 'phone'), ('email', 'email')], max_length=10, verbose_name='Select type')),
                ('value', models.CharField(max_length=40, verbose_name='Enter Contact')),
                ('url', models.CharField(max_length=50)),
                ('last_updated', models.DateField(auto_now=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
            ],
            options={
                'verbose_name_plural': 'Contact Detail',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('work', 'work'), ('home', 'home'), ('other', 'other')], max_length=10, verbose_name='Address Type')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('district', models.CharField(max_length=40, verbose_name='District')),
                ('pin', models.CharField(max_length=6, verbose_name='PIN')),
                ('state', models.CharField(max_length=40, verbose_name='State')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
                ('mapURL', models.URLField(blank=True, null=True, verbose_name='URL of MAP')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
            ],
            options={
                'verbose_name_plural': 'Address Detail',
            },
        ),
    ]
