# Generated by Django 3.2.6 on 2021-08-24 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('phone', 'phone'), ('email', 'email')], max_length=10, verbose_name='Select type')),
                ('value', models.CharField(max_length=120, verbose_name='Enter Contact')),
                ('url', models.URLField(verbose_name='URL')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
            ],
            options={
                'verbose_name_plural': 'Contact Detail',
            },
        ),
    ]
