# Generated by Django 3.2.6 on 2021-08-24 21:43

from django.db import migrations, models
import django.db.models.deletion
import home.helper
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('contact', '0005_auto_20210825_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('linkedin', 'linkedin'), ('whatsapp', 'whatsapp'), ('github', 'github'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram')], max_length=30, verbose_name='Address Type')),
                ('url', models.URLField(verbose_name='Social Media Link')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Image')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
            ],
            options={
                'verbose_name_plural': 'Social Account',
            },
        ),
    ]
