# Generated by Django 3.2.6 on 2021-08-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_socialaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='type',
            new_name='name',
        ),
    ]
