# Generated by Django 3.2.6 on 2021-08-25 07:27

from django.db import migrations, models
import home.helper


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_rename_type_socialaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='image_low_res',
            field=models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Account Image'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='name',
            field=models.CharField(choices=[('linkedin', 'linkedin'), ('whatsapp', 'whatsapp'), ('github', 'github'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram')], max_length=30, verbose_name='Social Media'),
        ),
    ]
