# Generated by Django 3.2.6 on 2021-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20210825_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='coutry',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='name',
            field=models.CharField(choices=[('linkedin', 'linkedin'), ('whatsapp', 'whatsapp'), ('github', 'github'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram')], error_messages={'unique': 'You already have added this social account.'}, max_length=30, unique=True, verbose_name='Social Media'),
        ),
    ]
