# Generated by Django 3.2.6 on 2021-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20210825_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='name',
            field=models.CharField(choices=[('linkedin', 'linkedin'), ('whatsapp', 'whatsapp'), ('github', 'github'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram')], max_length=30, verbose_name='Social Media'),
        ),
    ]
