# Generated by Django 3.2.6 on 2021-08-25 15:31

from django.db import migrations, models
import home.helper


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_socialaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='image_low_res',
            field=models.ImageField(blank=True, null=True, upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Account Image'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Social Media Link'),
        ),
    ]
