# Generated by Django 3.2.6 on 2021-08-25 17:05

from django.db import migrations, models
import django.utils.timezone
import home.helper


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20210825_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='image_low_res',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Account Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Social Media Link'),
            preserve_default=False,
        ),
    ]
