# Generated by Django 3.2.6 on 2021-08-21 12:04

from django.db import migrations, models
import home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('profile', 'Profile Picture'), ('award', 'Award'), ('social', 'Social Media'), ('project', 'Projects'), ('avataar', 'Avataar/Logo')], max_length=20, verbose_name='Image Type')),
                ('name', models.CharField(max_length=25, verbose_name='Name of Image')),
                ('alt', models.CharField(max_length=255, verbose_name='Alternative tag')),
                ('resolution', models.CharField(choices=[('LW', 'Low'), ('NL', 'Normal'), ('HG', 'High')], default='NL', max_length=3, verbose_name='Image Resolution')),
                ('image', models.ImageField(upload_to=home.models.image_directory_path, verbose_name='Upload Image')),
            ],
        ),
    ]
