# Generated by Django 3.2.6 on 2021-08-26 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.helper
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Mentor Name')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Profile Image')),
            ],
            options={
                'verbose_name_plural': 'Mentor',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bio', models.TextField(verbose_name='About Me')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('mentor', models.ManyToManyField(blank=True, to='home.Mentor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Technology Name')),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Technology',
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Profile Image Name')),
                ('image_high_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='High Resolution Profile Image')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Profile Image')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
            options={
                'verbose_name_plural': 'User Profile Image',
            },
        ),
        migrations.CreateModel(
            name='MentorChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, verbose_name='Channel Name')),
                ('url', models.URLField(verbose_name='Channel URL')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mentor')),
            ],
            options={
                'verbose_name_plural': 'Mentor Channel',
            },
        ),
    ]
