# Generated by Django 3.2.6 on 2021-08-25 20:14

from django.db import migrations, models
import django.db.models.deletion
import home.helper
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_high_res',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_low_res',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Profile Image Name')),
                ('image_high_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='High Resolution Profile Image')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Profile Image')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
            options={
                'verbose_name_plural': 'User Profile Image',
            },
        ),
    ]
