# Generated by Django 3.2.6 on 2021-08-21 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageuploader',
            options={'verbose_name_plural': 'Image Uploader'},
        ),
        migrations.AddField(
            model_name='imageuploader',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
