# Generated by Django 3.2.6 on 2021-08-21 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210821_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Technology Name')),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Technology',
            },
        ),
        migrations.AlterField(
            model_name='imageuploader',
            name='type',
            field=models.CharField(choices=[('profile', 'Profile Picture'), ('award', 'Award'), ('social', 'Social Media'), ('project', 'Project'), ('avataar', 'Avataar/Logo')], default='project', max_length=20, verbose_name='Image Type'),
        ),
    ]
