# Generated by Django 3.2.6 on 2021-08-28 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, verbose_name='Link Display Name')),
                ('url', models.URLField()),
                ('highlight', models.BooleanField(default=False, verbose_name='Highlight this link')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
            ],
            options={
                'verbose_name_plural': 'Quick Links',
            },
        ),
    ]
