# Generated by Django 3.2.6 on 2021-08-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210826_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mentor',
            field=models.ManyToManyField(blank=True, null=True, to='home.Mentor'),
        ),
    ]
