# Generated by Django 3.2.6 on 2021-09-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_profile_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickLink',
        ),
    ]
