# Generated by Django 3.2.6 on 2021-08-25 07:27

from django.db import migrations, models
import django.db.models.deletion
import home.helper
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Mentor Name')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Profile Image')),
            ],
            options={
                'verbose_name_plural': 'Mentor',
            },
        ),
        migrations.CreateModel(
            name='MentorChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, verbose_name='Channel Name')),
                ('url', models.URLField(verbose_name='Channel URL')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.mentor')),
            ],
            options={
                'verbose_name_plural': 'Mentor Channel',
            },
        ),
    ]
