# Generated by Django 3.2.6 on 2021-08-25 18:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import home.helper
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210826_0004'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Project Title')),
                ('slug', models.SlugField(blank=True, error_messages={'unique': 'Slug already exists'}, max_length=255, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='project URL')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='project URL')),
                ('source_code_url', models.URLField(blank=True, null=True, verbose_name='project URL')),
                ('image_high_res', models.ImageField(blank=True, null=True, upload_to=home.helper.image_directory_path, verbose_name='High Resolution Thumbnail Image')),
                ('image_low_res', models.ImageField(blank=True, null=True, upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Thumbnail Image')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
                ('tech_stack', models.ManyToManyField(to='home.Technology')),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Name of Project image')),
                ('image_high_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='High Resolution Project Image')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Project Image')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.RemoveField(
            model_name='mentorchannel',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='MentorChannel',
        ),
    ]
