# Generated by Django 3.2.6 on 2021-08-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210826_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='Project URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_code_url',
            field=models.URLField(blank=True, null=True, verbose_name='Source Code URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video Demo URL'),
        ),
    ]
