# Generated by Django 3.2.6 on 2021-08-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='source_code_url',
            field=models.URLField(blank=True, null=True, verbose_name='Source Code URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video Demo URL'),
        ),
    ]
