# Generated by Django 3.2.6 on 2022-03-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210827_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Hightlight Project'),
        ),
    ]
