# Generated by Django 3.2.6 on 2021-08-25 19:38

from django.db import migrations, models
import django.utils.timezone
import home.helper


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image_high_res',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=home.helper.image_directory_path, verbose_name='High Resolution Thumbnail Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image_low_res',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Thumbnail Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='source_code_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Source Code URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Video Demo URL'),
            preserve_default=False,
        ),
    ]
