# Generated by Django 3.2.6 on 2021-08-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210826_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
