# Generated by Django 3.2.6 on 2021-08-25 20:06

import ckeditor.fields
from django.db import migrations, models
import home.helper
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Award Name')),
                ('image_high_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='High Resolution Award Image')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Award Image')),
            ],
            options={
                'verbose_name_plural': "User's Award",
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Field Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('url', models.URLField(verbose_name='Field URL')),
                ('state', models.CharField(max_length=40, verbose_name='Passed out State')),
                ('tag', models.CharField(blank=True, choices=[('S', 'Secondary School'), ('HS', 'Higher Secondary School'), ('UG', 'Graduation'), ('PG', 'Post Graduation')], max_length=5, null=True, verbose_name='Type of Schooling')),
                ('short_descp', models.CharField(default='General Science', max_length=60, verbose_name='Small Description')),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.FloatField(help_text='Rating can be between 0 to 5', validators=[home.helper.validate_range], verbose_name='Skill Rating')),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': "User's Skill",
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Field Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('url', models.URLField(verbose_name='Field URL')),
                ('position', models.CharField(max_length=60, verbose_name='Work Position')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Logo Image')),
                ('detail', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Work Experience',
            },
        ),
    ]
