# Generated by Django 3.2.6 on 2021-08-21 09:27

import about.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_auto_20210821_1831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.FloatField(help_text='Rating can be between 0 to 5', validators=[about.models.MaxValueValidator], verbose_name='Skill Rating')),
                ('last_updated', models.DateField(auto_now=True)),
                ('technology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "User's Skill",
            },
        ),
    ]
