# Generated by Django 3.2.6 on 2021-08-23 11:38

import about.models
from django.db import migrations, models
import home.helper
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Award Name')),
                ('directory', models.CharField(default='award', editable=False, max_length=15)),
                ('image', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution')),
                ('img_high_res', models.ImageField(blank=True, null=True, upload_to=home.helper.image_directory_path)),
            ],
            options={
                'verbose_name_plural': "User's Awards",
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.FloatField(help_text='Rating can be between 0 to 5', validators=[about.models.MaxValueValidator], verbose_name='Skill Rating')),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': "User's Skill",
            },
        ),
    ]
