# Generated by Django 3.2.6 on 2021-08-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
        ),
        migrations.AddField(
            model_name='skill',
            name='technology',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.technology'),
        ),
        migrations.AddField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile'),
        ),
    ]
