# Generated by Django 3.2.6 on 2021-08-23 12:03

from django.db import migrations, models
import home.helper


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name_plural': "User's Award"},
        ),
        migrations.RemoveField(
            model_name='award',
            name='img_high_res',
        ),
        migrations.AddField(
            model_name='award',
            name='image_low_res',
            field=models.ImageField(default=models.ImageField(blank=True, null=True, upload_to=home.helper.image_directory_path), upload_to=home.helper.image_directory_path, verbose_name='Low Resolution'),
        ),
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.helper.image_directory_path),
        ),
    ]
