# Generated by Django 3.2.6 on 2021-08-23 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.helper


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('about', '0003_auto_20210823_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='image',
        ),
        migrations.AddField(
            model_name='award',
            name='image_high_res',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=home.helper.image_directory_path, verbose_name='High Resolution Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='image_low_res',
            field=models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Image'),
        ),
        migrations.AlterField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile'),
        ),
    ]
