# Generated by Django 3.2.6 on 2021-09-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_quicklink'),
        ('about', '0003_alter_skill_technology'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('profile', 'technology')},
        ),
    ]
