# Generated by Django 3.2.6 on 2021-08-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_remove_award_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='image_low_res',
        ),
    ]
