# Generated by Django 3.2.6 on 2021-08-24 20:02

from django.db import migrations, models
import home.helper


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_award_image_low_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image_low_res',
            field=models.ImageField(blank=True, null=True, upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Image'),
        ),
    ]
