# Generated by Django 3.2.6 on 2021-08-24 20:36

from django.db import migrations, models
import django.utils.timezone
import home.helper


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_award_image_low_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='image_low_res',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Image'),
            preserve_default=False,
        ),
    ]
