# Generated by Django 3.2.6 on 2021-08-25 08:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import home.helper
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_mentor'),
        ('about', '0009_auto_20210825_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Field Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('url', models.URLField(verbose_name='Field URL')),
                ('position', models.CharField(max_length=60, verbose_name='Work Position')),
                ('image_low_res', models.ImageField(upload_to=home.helper.image_directory_path, verbose_name='Low Resolution Logo Image')),
                ('detail', ckeditor.fields.RichTextField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Field Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('url', models.URLField(verbose_name='Field URL')),
                ('state', models.CharField(max_length=40, verbose_name='Passed out State')),
                ('tag', models.CharField(blank=True, choices=[('S', 'Secondary School'), ('HS', 'Higher Secondary School'), ('UG', 'Graduation'), ('PG', 'Post Graduation')], max_length=5, null=True, verbose_name='Type of Schooling')),
                ('short_descp', models.CharField(default='General Science', max_length=60, verbose_name='Small Description')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
